FirstProject/force-app/main/default/objects/Lead/fields/Count_Of_Outreaches__c.field-meta.xml
<CustomField>
    <fullName>Count_Of_Outreaches__c</fullName>
    <label>Count Of Outreaches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FirstProject/force-app/main/default/objects/Lead/fields/Count_of_successful_Outreaches__c.field-meta.xml
<CustomField>
    <fullName>Count_of_successful_Outreaches__c</fullName>
    <label>Count of successful Outreaches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FirstProject/force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreaches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreaches</relationshipLabel>
    <relationshipName>Outreaches</relationshipName>
    <type>Lookup</type>
</CustomField>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/classes/OutreachHelper.cls
public with sharing class OutreachHelper {

    public static void calculateOutreachesPerLeads(Set<Id> leadsToUpdateIds){
        List<Lead> leadsToUpdate = [SELECT Id, Name, Count_Of_Outreaches__c, Count_of_successful_Outreaches__c,
                                    (SELECT Id, Outcome__c FROM Outreaches__r)
                                    FROM Lead 
                                    WHERE Id IN :leadsToUpdateIds];
        for (Lead lead : leadsToUpdate) {
            Integer countOfSuccessfulOutreaches = 0;
            for (Outreach__c outr : lead.Outreaches__r) {
                if (outr.Outcome__c == 'Accepted' || outr.Outcome__c == 'Responded') {
                    countOfSuccessfulOutreaches++;
                }
            }
            lead.Count_Of_Outreaches__c = lead.Outreaches__r.size();
            lead.Count_of_successful_Outreaches__c = countOfSuccessfulOutreaches;
        }
        update leadsToUpdate;
    }

}