FirstProject/force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

FirstProject/force-app/main/default/classes/ProgramAssignmentController.cls
public with sharing class ProgramAssignmentController {
    @AuraEnabled
    public static List<Program_Assignment__c> getProgramAssignmentsByContact(String contactId, String objectName, String fieldSetName){
        System.debug(contactId);
        List<String> fields = new List<String>();
        for (Schema.FieldSetMember field : ServiceDeliveryController.getFieldSet(objectName, fieldSetName)) {
            fields.add(field.getFieldPath());
        }
        String queryStr = 'SELECT ' + String.join(fields, ', ') + ', Id, Program__r.Name, Contact__r.Name FROM Program_Assignment__c WHERE Contact__c = \'' + contactId + '\'';
        return Database.query(queryStr);
    }
}