FirstProject/force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreaches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreaches</relationshipLabel>
    <relationshipName>Outreaches</relationshipName>
    <type>Lookup</type>
</CustomField>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/classes/NeedAttentionLeadsBatch.cls
global with sharing class NeedAttentionLeadsBatch implements Database.Batchable<SObject>, Database.stateful {
    
    List<Lead> leadsNeedAttention = new List<Lead>();

    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Name, isConverted, CreatedDate, Need_Attention__c, (SELECT Id, Outcome__c FROM Outreaches__r) FROM Lead';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Lead> leads) {
        // Get successful Outcome statuses from Custom metadata type
        Set<String> outreachSuccessfulStatusesNames = NeedAttentionLeadsHelper.getSuccessfulOutcomeStatuses();
        List<Lead> leadsToUpdate = new List<Lead>();
        for (Lead lead : leads) {
            if (lead.Outreaches__r.isEmpty() && !lead.IsConverted) {
                NeedAttentionLeadsHelper.processLeadWithoutOutreaches(lead, leadsToUpdate, leadsNeedAttention);
            } else {
                NeedAttentionLeadsHelper.processLeadWithOutreaches(lead, outreachSuccessfulStatusesNames, leadsToUpdate, leadsNeedAttention);
            }
        }
        if (!leadsToUpdate.isEmpty()) {
            update leadsToUpdate;
        }
    }

    global void finish(Database.BatchableContext bc){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {UserInfo.getUserEmail()};
        String body = EmailSenderHelper.getEmailBody(leadsNeedAttention);
        mail.setTargetObjectId( UserInfo.getUserId() );
        mail.setSaveAsActivity( false );
        mail.setToAddresses(toAddresses);
        mail.setSubject('Leads Needing Attention: Batch Job Completed');
        mail.setHtmlBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}