FirstProject/force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreaches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreaches</relationshipLabel>
    <relationshipName>Outreaches</relationshipName>
    <type>Lookup</type>
</CustomField>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/classes/NeedAttentionLeadsHelper.cls
public with sharing class NeedAttentionLeadsHelper {
    
    public static Set<String> getSuccessfulOutcomeStatuses() {
        List<Successful_Outreach_Outcomes__mdt> allOutreachSuccessfulStatuses = Successful_Outreach_Outcomes__mdt.getAll().values();
        Set<String> outreachSuccessfulStatusesNames = new Set<String>();

        for (Successful_Outreach_Outcomes__mdt status : allOutreachSuccessfulStatuses) {
            outreachSuccessfulStatusesNames.add(status.DeveloperName);
        }

        return outreachSuccessfulStatusesNames;
    }
 
    public static void processLeadWithoutOutreaches(Lead lead, List<Lead> leadsToUpdate, List<Lead> leadsNeedAttention) {
        Date createdDate = lead.CreatedDate.date();
        Integer daysDifference = createdDate.daysBetween(Date.today());
        if (daysDifference > 3) {
            if (!lead.Need_Attention__c) {  // Only update Need_Attention__c if it is not already true
                lead.Need_Attention__c = true;
                leadsToUpdate.add(lead);
            }
            leadsNeedAttention.add(lead);
        }
    }

    
    public static void processLeadWithOutreaches(Lead lead, Set<String> outreachSuccessfulStatusesNames, List<Lead> leadsToUpdate, List<Lead> leadsNeedAttention) {
        Boolean hasOutreachWithSuccessfulOutcome = false;
        for (Outreach__c out : lead.Outreaches__r) {
            if (outreachSuccessfulStatusesNames.contains(out.Outcome__c)) {
                hasOutreachWithSuccessfulOutcome = true;
                break;
            }
        }
        if (!hasOutreachWithSuccessfulOutcome && !lead.IsConverted) {
            if (!lead.Need_Attention__c) { 
                lead.Need_Attention__c = true;
                leadsToUpdate.add(lead);
            }
            leadsNeedAttention.add(lead);
        } else if (hasOutreachWithSuccessfulOutcome && lead.Need_Attention__c) {
            lead.Need_Attention__c = false;  // Reset Need_Attention__c field if there's a successful outreach
            leadsToUpdate.add(lead);
        }
    }



}