FirstProject/force-app/main/default/objects/Outreach__c/Outreach__c.object-meta.xml
<CustomObject>
    <label>Outreach</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Outreach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreaches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Communication_Method__c.field-meta.xml
<CustomField>
    <fullName>Communication_Method__c</fullName>
    <label>Communication Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
                <default>true</default>
                <label>Phone</label>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Outreaches</relationshipLabel>
    <relationshipName>Outreaches</relationshipName>
    <type>Lookup</type>
</CustomField>

FirstProject/force-app/main/default/objects/Outreach__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Responded</fullName>
                <default>true</default>
                <label>Not Responded</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/classes/LeadsSchedulerTest.cls
@isTest
private with sharing class LeadsSchedulerTest {

    @isTest
    private static void testLeadScheduler_LeadHasNoOutreaches(){
       List<Lead> leads = TestDataFactory.createMultipleLeadsWithPresetNeedAttention(5, false);
       insert leads;
       for (Lead lead : leads) {
           Test.setCreatedDate(lead.Id, DateTime.now().addDays(-4));
       }
               
        String jobId = System.schedule('Test Scheduled Batch', '0 0 0 * * ?', new LeadsScheduler());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals('0 0 0 * * ?', ct.CronExpression);

        Test.startTest();
        Database.executeBatch(new NeedAttentionLeadsBatch());
        Test.stopTest();

        List<Lead> updatedLead = [SELECT Id, Name, Need_Attention__c FROM Lead];
        for (Lead l : updatedLead) {
            System.assert(l.Need_Attention__c, 'Leads must have Need_Attention__c field true');

        }
    }

    @isTest
    private static void testLeadScheduler_LeadHasUnsuccessfulOutreaches(){
        List<Lead> leads = TestDataFactory.createMultipleLeadsWithPresetNeedAttention(5, false);
        insert leads;
        List<Outreach__c> testOutreaches = new List<Outreach__c>();
        for (Integer i = 0; i < 5; i++) {
            testOutreaches.add(new Outreach__c(Outcome__c='Not Responded', 
                                              Lead__c=leads[i].Id, 
                                              Communication_Method__c='Email'));
        }
        
        insert testOutreaches;

        Test.startTest();
        Database.executeBatch(new NeedAttentionLeadsBatch());
        Test.stopTest();

        List<Lead> updatedLead = [SELECT Id, Name, Need_Attention__c FROM Lead];
        for (Lead l : updatedLead) {
            System.assert(l.Need_Attention__c, 'Leads must have Need_Attention__c field true');
        }

    }

    @isTest
    private static void testLeadScheduler_LeadHasSuccessfulOutreachesAndNeedAttentionChecked(){
        List<Lead> leads = TestDataFactory.createMultipleLeadsWithPresetNeedAttention(5, true);
        insert leads;
        List<Outreach__c> testOutreaches = new List<Outreach__c>();
        for (Integer i = 0; i < 5; i++) {
            testOutreaches.add(new Outreach__c(Outcome__c='Responded', 
                                              Lead__c=leads[i].Id, 
                                              Communication_Method__c='Email'));
        }
        insert testOutreaches;

        Test.startTest();
        Database.executeBatch(new NeedAttentionLeadsBatch());
        Test.stopTest();

        List<Lead> updatedLeads = [SELECT Id, Name, Need_Attention__c FROM Lead];
        for (Lead l : updatedLeads) {
            System.assert(!l.Need_Attention__c, 'Leads must have Need_Attention__c field false');
        }

    }


}