FirstProject/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/objects/Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Skill</fullName>
            </value>
            <value>
                <fullName>Help</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

FirstProject/force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Contact> createContacts(Integer count){
        List<Contact> contacts = new List<Contact>();
        for(Integer i = 0; i < count; i++){
            contacts.add(new Contact(LastName='Test Contact ' + i));
        }
        insert contacts;
        
        return contacts;
    }
    
    public static List<Program__c> createPrograms(Integer count){
        List<Program__c> programs = new List<Program__c>();
        for(Integer i = 0; i < count; i++){
            programs.add(new Program__c(Name='Test Program ' + i, Type__c='Skill', Status__c='Active'));
        }
        insert programs;
        
        return programs;
    }
    public static Program_Assignment__c createTestProgramAssignment(Id contactId, Id programId, Date startDate, String status, Boolean autoName) {
        Program_Assignment__c testPA = new Program_Assignment__c(
            Contact__c = contactId,
            Program__c = programId,
            Start_Date__c = startDate,
            Status__c = status,
            Autoname__c = autoName
        );
        return testPA;
    }
    public static List<Program_Assignment__c> createMultipleProgramAssignments(Id contactId, Id programId, String status, Integer count) {
        List<Program_Assignment__c> programAssignments = new List<Program_Assignment__c>();
        for (Integer i = 0; i < count; i++) {
            programAssignments.add(new Program_Assignment__c(
                Contact__c = contactId,
                Program__c = programId,
                Status__c = status,
                Start_Date__c = Date.today(),
                Autoname__c = true
            ));
        }
        insert programAssignments;
        return programAssignments;
    }
    
}