FirstProject/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FirstProject/force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FirstProject/force-app/main/default/classes/ProgramTriggerHandler.cls
public with sharing class ProgramTriggerHandler extends TriggerHandler {

    List<Program__c> newPrograms;
    List<Program__c> oldPrograms;
    Map<Id, Program__c> oldProgramsMap;

    public ProgramTriggerHandler() {
        newPrograms = (List<Program__c>) Trigger.new;
        oldPrograms = (List<Program__c>) Trigger.old;
        oldProgramsMap = (Map<Id, Program__c>) Trigger.oldMap;
    }


    public override void afterUpdate(){
        Set<Id> programIdsPAToUpdate = new Set<Id>();
        for (Program__c p : newPrograms) {
            Program__c oldProgram = oldProgramsMap.get(p.Id);
            if (oldProgram.Name != p.Name) {
                programIdsPAToUpdate.add(p.Id);
            }
        }
        if (!programIdsPAToUpdate.isEmpty()) {
            ProgramAssignmentHelper.updateRelatedProgramAssignments(programIdsPAToUpdate, 'Program__c');            
        }
    }


    public override void beforeDelete() {
        Set<Id> programIds = oldProgramsMap.keySet();
        List<Program_Assignment__c> programRelatedPAs = SOQLHelper.getRelatedProgramAssignments(programIds,'Program__c');
        List<Program_Assignment__c> pasToDelete = new List<Program_Assignment__c>();

        for (Program_Assignment__c pa : programRelatedPAs) {
            if (pa.Status__c != 'Denied' && pa.Status__c != 'Applied') {
                Program__c pr = oldProgramsMap.get(pa.Program__c);
                pr.addError('Cannot Delete Program because it has PAs with Status ' + pa.Status__c);
            }else {
                pasToDelete.add(pa);
            }
        }
        if (!pasToDelete.isEmpty()) {
            delete pasToDelete;
        }
        
    }



}